## Data Science Bootcamp

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 201](#1)
* [Ćwiczenie 202](#2)
* [Ćwiczenie 203](#3)
* [Ćwiczenie 204](#4)
* [Ćwiczenie 205](#5)
* [Ćwiczenie 206](#6)
* [Ćwiczenie 207](#7)
* [Ćwiczenie 208](#8)
* [Ćwiczenie 209](#9)
* [Ćwiczenie 210](#10)

### <a name='0'></a>Import biblioteki

In [1]:
import numpy as np
import pandas as pd

np.__version__

'1.19.5'

### <a name='1'></a> Ćwiczenie 201
Z poniższego słownika _data_ utwórz obiekt _DataFrame_ i przypisz do zmiennej _df_.

In [24]:
data = {
    'size': ['XL', 'L', 'M', np.nan, 'M', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red', 'green'],
    'gender': ['female', 'male', np.nan, 'female', 'female', 'male'],
    'price': [199.0, 89.0, np.nan, 129.0, 79.0, 89.0],
    'weight': [500, 450, 300, np.nan, 410, np.nan],
    'bought': ['yes', 'no', 'yes', 'no', 'yes', 'no']
}

df = pd.DataFrame(data)

Wyświetl podstawowe informacje na temat obiektu _df_.

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   size    5 non-null      object
 1   color   6 non-null      object
 2   gender  5 non-null      object
 3   price   5 non-null      float64
 4   weight  4 non-null      float64
 5   bought  6 non-null      object
dtypes: float64(2), object(4)
memory usage: 416.0+ bytes

### <a name='2'></a> Ćwiczenie 202
Sprawdź liczbę braków danych dla poszczególnych zmiennych.

In [26]:
df.isnull().sum()

size      1
color     0
gender    1
price     1
weight    2
bought    0
dtype: int64

Sprawdź liczbę braków danych dla poszczególnych zmiennych. Podaj procent braków.

In [27]:
for col in df.columns:
    print(f'{col}: {round((df[col].isnull().sum() / len(df[col]) *100),2)} %')

size: 16.67 %
color: 0.0 %
gender: 16.67 %
price: 16.67 %
weight: 33.33 %
bought: 0.0 %

### <a name='3'></a> Ćwiczenie 203
Wykorzystując bibliotekę do uczenia maszynowego _scikit-learn_ oraz klasę _SimpleImputer_ uzupełnij braki danych dla zmiennej _weight_ wartością średnią. Zmiany przypisz na stałe do obiektu _df_.

In [28]:
from sklearn.impute import SimpleImputer

si = SimpleImputer(missing_values=np.nan, strategy='mean')
df[['weight']] = si.fit_transform(df[['weight']])

Wyświetl wartość średnią wstawioną w miejsce braków kolumny _weight_.

In [29]:
si.statistics_

array([415.])

### <a name='4'></a> Ćwiczenie 204
Wykorzystując bibliotekę do uczenia maszynowego _scikit-learn_ oraz klasę _SimpleImputer_ uzupełnij braki danych dla zmiennej _price_ stałą wartością 99.0. Zmiany przypisz na stałe do obiektu _df_.

In [30]:
si = SimpleImputer(missing_values=np.nan, strategy='constant', fill_value=99.0)
df[['price']] = si.fit_transform(df[['price']])
df

  size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN   99.0   300.0    yes
3  NaN  green  female  129.0   415.0     no
4    M    red  female   79.0   410.0    yes
5    M  green    male   89.0   415.0     no

### <a name='5'></a> Ćwiczenie 205
Wykorzystując bibliotekę do uczenia maszynowego _scikit-learn_ oraz klasę _SimpleImputer_ uzupełnij braki danych dla zmiennej _size_ najczęściej pojawiającym się elementem. Zmiany przypisz na stałe do obiektu _df_.

In [31]:
si = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
df[['size']] = si.fit_transform(df[['size']])
df

  size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN   99.0   300.0    yes
3    M  green  female  129.0   415.0     no
4    M    red  female   79.0   410.0    yes
5    M  green    male   89.0   415.0     no

### <a name='6'></a> Ćwiczenie 206
Przed przejściem do następnych ćwiczeń ponownie załaduj słownik do obiektu _df_.

In [36]:
df = pd.DataFrame(data)
df

  size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN    NaN   300.0    yes
3  NaN  green  female  129.0     NaN     no
4    M    red  female   79.0   410.0    yes
5    M  green    male   89.0     NaN     no

Wytnij wszystkie wiersze obiektu _df_ dla których zmienna _weight_ przyjmuje wartość _np.nan_.

In [43]:
df[df['weight'].isnull()]

  size  color  gender  price  weight bought
3  NaN  green  female  129.0     NaN     no
5    M  green    male   89.0     NaN     no

Wytnij wszystkie wiersze obiektu _df_ dla których zmienna _weight_ nie przyjmuje wartość _np.nan_.

In [44]:
df[~df['weight'].isnull()]

  size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN    NaN   300.0    yes
4    M    red  female   79.0   410.0    yes

### <a name='7'></a> Ćwiczenie 207
Uzupełnij wszystkie braki  w obiekcie _df_ wartością 'brak'. Zmian nie przypisuj na stałe do zmiennej _df_.

In [45]:
df['weight'].fillna('brak')

0     500
1     450
2     300
3    brak
4     410
5    brak
Name: weight, dtype: object

### <a name='8'></a> Ćwiczenie 208
Usuń wiersze z brakami danych z obiektu _df_. Zmian nie przypisuj na stałe do zmiennej _df_.

In [46]:
df.dropna()

  size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
4    M    red  female   79.0   410.0    yes

### <a name='9'></a> Ćwiczenie 209
Usuń wiersze z brakami danych z obiektu _df_ dla których nie ma co najmniej 5 zdefiniowanych wartości (inaczej zawierają dwa braki _np.nan_). Zmian nie przypisuj na stałe do zmiennej _df_.

In [48]:
df.dropna(thresh=5)

  size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
4    M    red  female   79.0   410.0    yes
5    M  green    male   89.0     NaN     no

### <a name='10'></a> Ćwiczenie 210
Usuń wiersze z brakami danych z obiektu _df_ dla których nie ma co najmniej 5 zdefiniowanych wartości (inaczej zawierają dwa braki _np.nan_) a resztę braków wypełnij stałą wartością 400.0. Zmian nie przypisuj na stałe do zmiennej _df_.

In [49]:
df.dropna(thresh=5).fillna(400.0)

  size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
4    M    red  female   79.0   410.0    yes
5    M  green    male   89.0   400.0     no